version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/services"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "pub"
    directory: "/mobile"
    schedule:
      interval: "weekly"