services:
  - type: web
    name: usuarios-api
    env: docker
    dockerContext: .
    dockerfilePath: services/Usuarios.Api/Dockerfile
    envVars:
      - key: Supabase__Url
        sync: false
      - key: Supabase__AnonKey
        sync: false
      - key: Supabase__ServiceRoleKey
        sync: false
    # Mantenemos el contexto en la raíz (.) para poder copiar HavenApi.Shared

  # - type: web
  #   name: viviendas-api
  #   env: docker
  #   dockerContext: .
  #   dockerfilePath: services/Viviendas.Api/Dockerfile
  #   envVars:
  #     - key: Supabase__Url
  #       sync: false
  #     - key: Supabase__AnonKey
  #       sync: false
  #     - key: Supabase__ServiceRoleKey
  #       sync: false

  # - type: web
  #   name: condominios-api
  #   env: docker
  #   dockerContext: .
  #   dockerfilePath: services/Condominios.Api/Dockerfile
  #   envVars:
  #     - key: Supabase__Url
  #       sync: false
  #     - key: Supabase__AnonKey
  #       sync: false
  #     - key: Supabase__ServiceRoleKey
  #       sync: false
