name: Auto Git Flow (Format & Commit)

on:
  workflow_dispatch:
  push:
    branches:
      - mobilepipe

jobs:
  auto-format-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Format code
        run: dart format lib test integration_test

      - name: Check for modifications
        id: git-check
        working-directory: .
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto Commit and Push
        if: steps.git-check.outputs.changes == 'true'
        working-directory: .
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          BRANCH_NAME="auto-format-$(date +%s)"
          
          # Checkout -b
          git checkout -b $BRANCH_NAME
          
          # Add changes
          git add .
          
          # Commit
          git commit -m "style: auto format dart code"
          
          # Push origin
          git push origin $BRANCH_NAME
          
          # Notificación opcional de Discord sobre el nuevo branch
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "🔄 Auto Git Flow: Branch Created",
              "description": "Se ha creado la rama `'$BRANCH_NAME'` con correcciones automáticas de formato.",
              "color": 3447003
            }]
          }' \
          https://discord.com/api/webhooks/1545292672137302078/sRjwddHW0pXAndT-B7Wj6QFGC5CV6I52q9r1SyMiRKcMaAk1_LuGkDTVp5hnauQysobO
